# Generated by Django 4.0.4 on 2022-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('remarque', models.TextField()),
                ('note', models.IntegerField()),
                ('image', models.ImageField(default='img/default.jpg', upload_to='img/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('type_element', models.CharField(choices=[('D', 'Disney'), ('F', 'Film'), ('S', 'Série')], max_length=1)),
            ],
        ),
    ]
