# Generated by Django 4.0.4 on 2022-06-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_element_decouvrir_element_favori_element_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='decouvrir',
        ),
        migrations.RemoveField(
            model_name='element',
            name='favori',
        ),
    ]
