# Generated by Django 4.0.4 on 2022-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_remove_element_decouvrir_remove_element_favori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='test',
        ),
        migrations.AddField(
            model_name='element',
            name='acheter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='element',
            name='decouvrir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='element',
            name='favori',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='element',
            name='revoir',
            field=models.BooleanField(default=False),
        ),
    ]
