# Generated by Django 4.0.4 on 2022-06-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_remove_element_test_element_acheter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='url',
            field=models.URLField(default='https://i.pinimg.com/originals/a5/18/aa/a518aadd234b7dfacd710a6c0c1a2227.jpg'),
        ),
        migrations.AlterField(
            model_name='element',
            name='decouvrir',
            field=models.BooleanField(default=False, verbose_name='Découvrir'),
        ),
    ]
