# Generated by Django 4.0.4 on 2022-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_element_url_alter_element_decouvrir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='element',
            name='url',
            field=models.URLField(),
        ),
    ]
